// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPBibKEIMmHwJZDnAUSHbS4ASaC5fuik',
    appId: '1:693007379589:web:5b68617cf59b7bfd9c8dec',
    messagingSenderId: '693007379589',
    projectId: 'zingdibloodappdb',
    authDomain: 'zingdibloodappdb.firebaseapp.com',
    storageBucket: 'zingdibloodappdb.appspot.com',
    measurementId: 'G-T25SPF8WZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ca7-ZmNpW0shAZQYP2Ea3J8KFFpDtG8',
    appId: '1:693007379589:android:8d62bf82c51eb8129c8dec',
    messagingSenderId: '693007379589',
    projectId: 'zingdibloodappdb',
    storageBucket: 'zingdibloodappdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrPp2NO-90EttiOpg11ifqyny0NWSxYc',
    appId: '1:693007379589:ios:3eb1cd5551f381319c8dec',
    messagingSenderId: '693007379589',
    projectId: 'zingdibloodappdb',
    storageBucket: 'zingdibloodappdb.appspot.com',
    iosBundleId: 'com.example.zindgibloodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfrPp2NO-90EttiOpg11ifqyny0NWSxYc',
    appId: '1:693007379589:ios:502ada9ae576a2429c8dec',
    messagingSenderId: '693007379589',
    projectId: 'zingdibloodappdb',
    storageBucket: 'zingdibloodappdb.appspot.com',
    iosBundleId: 'com.example.zindgibloodapp.RunnerTests',
  );
}
